Nsample:
	cp sample_vmc_helium4_Nsample.jl 1 & \
	cp sample_vmc_helium4_Nsample.jl 2 & \
	cp sample_vmc_helium4_Nsample.jl 3 & \
	cp sample_vmc_helium4_Nsample.jl 4 & \
	cp sample_vmc_helium4_Nsample.jl 5 & \
	cp sample_vmc_helium4_Nsample.jl 6 & \
	cp sample_vmc_helium4_Nsample.jl 7 & \
	cp sample_vmc_helium4_Nsample.jl 8 & \
	cp sample_vmc_helium4_Nsample.jl 9 & \
	cp sample_vmc_helium4_Nsample.jl 10 & \
	cd 1 && julia sample_vmc_helium4_Nsample.jl	& cd .. & \
	cd 2 && julia sample_vmc_helium4_Nsample.jl	& cd .. & \
	cd 3 && julia sample_vmc_helium4_Nsample.jl	& cd .. & \
	cd 4 && julia sample_vmc_helium4_Nsample.jl	& cd .. & \
	cd 5 && julia sample_vmc_helium4_Nsample.jl	& cd .. & \
	cd 6 && julia sample_vmc_helium4_Nsample.jl	& cd .. & \
	cd 7 && julia sample_vmc_helium4_Nsample.jl	& cd .. & \
	cd 8 && julia sample_vmc_helium4_Nsample.jl	& cd .. & \
	cd 9 && julia sample_vmc_helium4_Nsample.jl	& cd .. & \
	cd 10 && julia sample_vmc_helium4_Nsample.jl & cd .. & \

Sampleclean:
	rm -f 1/sample_vmc_helium4_Nsample.jl &
	rm -f 2/sample_vmc_helium4_Nsample.jl	&
	rm -f 3/sample_vmc_helium4_Nsample.jl	&
	rm -f 4/sample_vmc_helium4_Nsample.jl	&
	rm -f 5/sample_vmc_helium4_Nsample.jl	&
	rm -f 6/sample_vmc_helium4_Nsample.jl	&
	rm -f 7/sample_vmc_helium4_Nsample.jl	&
	rm -f 8/sample_vmc_helium4_Nsample.jl	&
	rm -f 9/sample_vmc_helium4_Nsample.jl	&
	rm -f 10/sample_vmc_helium4_Nsample.jl &	
